id_curso_cursos = {
    "2": "Técnico en redes de datos",
    "4": "Carpintero",
    "5": "Asistente de Mesero",
    "6": "Aseador de oficina",
    "8": "Planchador",
    "9": "Albañil",
    "11": "Herrero, balconero, aluminador y forjador",
    "12": "Plomeros, fontaneros e instaladores de tubería",
    "14": "Cajero de restaurante",
    "15": "Cuidador de adultos mayores",
    "16": "Asistente web",
    "18": "Vendedor por catálogo",
    "20": "Jardinero a gran escala",
    "21": "Almacenista-montacarguista",
    "22": "Técnico Minero",
    "23": "Instalador de pisos de loseta ",
    "24": "Pintor",
    "25": "Cuidador de niños ",
    "26": "Cocinero",
    "27": "Reparador de aire acondicionado",
    "28": "Curador de datos",
    "29": "Instalador de tejados",
    "30": "Instalador de paneles de yeso ",
    "31": "Técnico en cultivos vegetales",
    "32": "Bartender",
    "33": "Técnico procesador de frutas y verduras",
    "35": "Panadero",
    "36": "Mecánico automotriz",
    "37": "Corte y confección",
    "38": "Lavaplatos",
    "39": "Empleado de comida rápida",
    "40": "Asesor de Belleza",
    "41": "Conductor de transporte público",
    "42": "Desarrollador de contenido digital",
    "43": "Finder",
    "44": "Gestor de Imagen Web",
    "45": "Visualizador de Big Data",
    "46": "Tester",
    "47": "Instalador de fibra óptica",
    "48": "Vendedor de piso",
    "49": "Técnico en seguridad informática (análisis de riesgos)",
    "50": "Técnico en electrónica",
    "51": "Agente de ventas digital",
    "52": "Granjero de lechería (ordeña y alimentación)",
    "54": "Conductor de Transporte Ejecutivo",
    "55": "Representante telefónico",
    "56": "Mesero",
    "57": "Trabajador doméstico",
    "58": "Encargado de envoltura de regalos",
    "62": "Banderero",
    "63": "Cajero de tienda de autoservicio",
    "66": "Ideas para crecer tu negocio",
    "67": "Guía para entrevistas de trabajo",
    "69": "Administrador de bases de datos",
    "70": "Instalador de cables de cobre",
    "71": "Programador (orientado a objetos)",
    "75": "Analista de necesidades de formación",
    "76": "Administrador de servidores",
    "77": "Bodeguero (Restaurante)",
    "78": "Jefe de cocina",
    "79": "Movilidad motorizada",
    "80": "Movilidad No Motorizada",
    "81": "Analista de datos",
    "82": "Administrador de proyectos para ambientes virtuales de aprendizaje",
    "83": "Desarrollador de contenidos de aprendizaje",
    "84": "Facilitador de aprendizaje digital ",
    "85": "Arquitecto de ambientes virtuales de aprendizaje ",
    "86": "Técnico en cultivo de vegetales orgánicos ",
    "88": "Introducción a la facilitación presencial en pequeños grupos",
    "89": "Programa de educación financiera",
    "90": "La trascendencia del educador durante la primera infancia",
    "93": "Conoce el micromenudeo",
    "95": "Cosecha y cultivo de agua",
    "96": "Servidor público",
    "97": "Steward",
    "98": "Operador de autotransporte",
    "99": "Jefe de mantenimiento",
    "101": "Mejora de procesos",
    "103": "Vida Saludable",
    "104": "Evaluador de aprendizaje digital",
    "105": "Evaluador de Ambientes Virtuales de Aprendizaje",
    "106": "Embalado",
    "107": "Empaquetado",
    "108": "Envasado",
    "109": "Introducción a la economía",
    "110": "Tecnologías de la Información para servidor público",
    "111": "Desarrollador de videojuegos",
    "113": "Bolsa de valores",
    "114": "Mecánico de bicicletas",
    "115": "Derechos Humanos para el Servidor Público",
    "116": "Fundamentos del trastorno del espectro autista",
    "117": "Etiquetado",
    "118": "Negocios móviles",
    "120": "Manejo higiénico de los alimentos",
    "121": "Desarrollador Back-end",
    "122": "Desarrollador Front-end",
    "123": "Administrador de plataformas digitales de aprendizaje",
    "127": "Salud Digital",
    "128": "Técnico en manejo de residuos sólidos urbanos",
    "129": "Ahorro de energía (casa y oficina)",
    "130": "Técnico en reciclaje",
    "131": "Instalador de techos verdes",
    "132": "Diseñador de experiencia de usuario (UX)",
    "133": "Desarrollador de interfaces gráficas",
    "134": "Técnico en reparación de laptops",
    "135": "Técnico en seguridad informática (servidores)",
    "136": "Asesor de energías renovables",
    "137": "Servicio de barbería (Barba y bigote)",
    "138": "Estilista",
    "140": "Instalador de paneles solares",
    "141": "Consumo responsable",
    "142": "Ciudadano global",
    "143": "Mercadotecnia digital",
    "144": "Anfitrión Turístico",
    "145": "Promotor en prevención de accidentes",
    "146": "Diseñador de circuitos impresos (PCB)",
    "147": "Lógica de programación",
    "148": "Programador de microcontroladores ",
    "149": "Programador de microordenadores",
    "150": "Promotor de artículos orgánicos",
    "151": "Liderazgo",
    "152": "Auxiliar Operativo",
    "153": "Exhibición de productos",
    "155": "Supervisor de operaciones ",
    "156": "Evaluación de ideas de negocios",
    "157": "Estrategia formal de autoempleo",
    "158": "Formulación y evaluación de proyectos",
    "159": "Cómo calcular tu inversión",
    "160": "Estándares de calidad",
    "161": "Ecología industrial",
    "162": "Diseño de indicadores",
    "163": "Plan de producción",
    "164": "Bienestar ocupacional",
    "165": "Relaciones profesionales",
    "166": "Relaciones comerciales",
    "167": "Contabilidad empresarial",
    "168": "Formalización de tu negocio",
    "169": "Comercialización y distribución",
    "170": "Comercio digital",
    "171": "Plan de exportación",
    "173": "Experto MIDO niñas, niños y adolescentes",
    "174": "Fundamentos del cómputo en la nube",
    "175": "Formación para conductores",
    "177": "El aprendizaje en los adultos",
    "178": "Auxiliar contable",
    "180": "Cómo integrar el perfil de un cliente",
    "181": "Fundamentos de virtualización",
    "182": "Niñas y Niños Creciendo Sanos y Listos",
    "183": "Diseñador de oferta turística",
    "184": "Fundamentos de electrónica digital",
    "185": "Asesor de lactancia materna",
    "186": "Transformando conflictos",
    "187": "Autoconstrucción",
    "188": "Promotor turístico",
    "189": "Evaluador de procesos",
    "190": "Técnico en minería de datos",
    "191": "Técnico en seguridad en la nube",
    "192": "Técnico en redes IP",
    "193": "Asesor de servicios de infraestructura en la nube",
    "194": "Evaluador de Indicadores Clave (KPI)",
    "195": "Técnico en Business Analytics",
    "196": "Visualizador de datos",
    "197": "Técnico en comunicaciones inalámbricas",
    "198": "Fundamentos de la red 4.5G",
    "199": "Fundamentos de la red 5G",
    "201": "Barista",
    "202": "Profesionalización del autotransporte",
    "203": "Operación de flotas eficientes",
    "204": "Cadena de suministro y costo del autotransporte",
    "205": "Guía de autoconstrucción",
    "206": "Guía de reparación vivienda rural",
    "211": "Mejora tu ortografía y redacción",
    "212": "Disciplina en el trabajo",
    "213": "Cómputo básico",
    "215": "Promotor del desarrollo infantil",
    "216": "Investigación empresarial",
    "217": "Cálculo de huella de carbono",
    "218": "Cálculo de huella ecológica",
    "219": "Administrador de la nube",
    "221": "¿Cómo debo cuidarme si estoy embarazada y tengo diabetes?",
    "222": "Control de versiones",
    "223": "Desarrollo móvil en línea",
    "224": "Desarrollador de sitios web responsivos",
    "225": "Preprocesadores de estilo",
    "226": "Desarrollador de aplicaciones en la nube",
    "227": "Razones por las que te elige o descarta una empresa",
    "228": "Estructura de un CV",
    "229": "Integrador de soluciones BI",
    "230": "Analista de proyectos BI",
    "231": "Analista técnico en TI",
    "232": "Facilitador ASUME",
    "233": "Cálculo de huella hídrica",
    "234": "Protocolos de atención y servicio",
    "235": "Auxiliar en la calidad del aire en interiores",
    "236": "Gobernanza del aire",
    "237": "Técnico en instalación de energía eólica",
    "239": "Técnico auxiliar en lactancia materna",
    "240": "Técnico topógrafo ",
    "241": "Productor de grillos",
    "242": "Promotor en activación física",
    "244": "Técnico en instalación de calentadores solares ",
    "245": "Introducción al ecoturismo",
    "246": "Introducción a la programación",
    "247": "Administrador de bases de datos no relacionales ",
    "248": "Técnico en construcción y reparación de drones",
    "249": "Operador de impresoras 3D",
    "250": "Fundamentos de electrónica analógica ",
    "251": "Instalador de Home Networking ",
    "252": "Técnico en seguridad informática perimetral",
    "253": "Fundamentos de seguridad informática",
    "254": "Seguridad en dispositivos móviles y aplicativos (datos personales)",
    "255": "Fundamentos de tecnologías 4K y OTT",
    "256": "Gobernanza TI",
    "257": "Reparador de TV de plasma y LCD",
    "258": "Prácticas de ofimática",
    "262": "Cómo dar indicaciones",
    "263": "Trabajo en equipo",
    "268": "Fundamentos de Machine Learning",
    "271": "Seguridad e Higiene en ambiente laboral",
    "272": "Técnico en instalación y reparación de equipo de cómputo",
    "273": "Manejo de juntas de trabajo",
    "274": "Gobernanza del agua",
    "275": "Cultura ambiental",
    "276": "Voluntario",
    "277": "Programador en C#",
    "280": "Apicultor",
    "281": "Productor de traspatio para autoconsumo",
    "282": "Elaboración de composta",
    "283": "Informes ejecutivos",
    "284": "Habilidades de presentación",
    "285": "Prácticas de mecanografía",
    "286": "Cuidados paliativos (familiares y voluntarios)",
    "287": "¿Cómo cuidarme para un embarazo saludable?",
    "288": "¿Cómo debo cuidar mis pies si vivo con diabetes?",
    "291": "Finanzas personales",
    "292": "Técnico en seguridad host (escritorio)",
    "293": "Técnico en informática (Ofimática)",
    "298": "Constructor de paz",
    "299": "Cultura urbana",
    "300": "Almacenamiento de energías renovables en baterías",
    "301": "Protocolos de venta ",
    "302": "Fundamentos de estructura de datos ",
    "303": "Facilitador de grupos ",
    "304": "Jugar para crecer",
    "305": "Prácticas de cortesía",
    "306": "Cultura económica (Introducción)",
    "307": "Discapacidad en la primera infancia",
    "309": "Ergonometría digital",
    "310": "Concentración de agentes contaminantes en el aire ",
    "311": "Técnico instalador de cableado estructurado",
    "312": "Lengua de señas mexicana",
    "313": "Cultura económica (PIB)",
    "314": "Manejo manual de cargas",
    "315": "Reparador de celulares y tabletas",
    "318": "Cultura económica (Inflación)",
    "319": "Huella digital",
    "320": "Funcionamiento CoDi",
    "321": "Responsabilidad digital",
    "322": "Asesor de generación de residuos cero",
    "323": "Economía circular",
    "342": "Introducción a Primer Respondiente",
    "343": "Tu negocio en Internet",
    "344": "Tus Clientes en Internet",
    "345": "Transacciones electrónicas",
    "346": "¿Trabajo remoto?",
    "347": "Consumo sostenible",
    "348": "Seguridad para todas y todos",
    "349": "Paradigma de programación (orientado a objetos)",
    "350": "Diseñador de objetos para impresión 3D",
    "351": "Nueva interacción urbana",
    "352": "Movilidad de baja densidad",
    "354": "Potabilización del agua",
    "355": "Responsabilidad digital (Trabajo remoto)",
    "356": "Desarrollador de JavaScript (Node JS)",
    "357": "Síndrome de Down: El Espacio de Michelle",
    "358": "Networking digital",
    "359": "Analista de optimización en motores de búsqueda (SEO)",
    "360": "Analista en mercadotecnia de motores de búsqueda (SEM)",
    "361": "Técnico en agua residual (doméstico)",
    "362": "Buenas prácticas para el uso de telemedicina",
    "364": "Decisiones inteligentes para la protección del medio ambiente",
    "366": "Fundamentos de blockchain",
    "367": "Electricista",
    "368": "Uso de código QR",
    "369": "Fundamentos de redes definidas por software (SDN)",
    "370": "Transformación digital y evolución tecnológica",
    "371": "Uso responsable de dispositivos electrónicos",
    "372": "Uso del correo electrónico",
    "373": "Regulación de la interacción digital",
    "374": "Seguridad y privacidad en el manejo de información (Regulación)",
    "375": "Prevención de delitos cibernéticos",
    "376": "Netiqueta",
    "377": "Evaluador de experiencia de usuario (UX)",
    "378": "Economía naranja",
    "379": "Conexión a internet en el hogar",
    "380": "Operación de banca en línea",
    "382": "Medidas de higiene, prevención y contención de contagios",
    "384": "Finanzas para invertir",
    "385": "Mercados financieros",
    "387": "Buenas prácticas para el ahorro de agua",
    "388": "Recuperación de cuerpos de agua",
    "389": "Cimentación de una obra",
    "390": "Diseño de interiores",
    "391": "Yo prevengo la violencia",
    "392": "Postprocesadores de estilo",
    "393": "Uso de aplicaciones de emergencia",
    "394": "Comunicación por videollamadas",
    "395": "Habilidades de negociación",
    "397": "Manejo ético de la información y datos",
    "398": "Uso de información y datos",
    "399": "Uso de interfaz de dispositivos móviles",
    "405": "Planea la búsqueda de información",
    "406": "Técnico en comunicaciones por microondas",
    "407": "Crecer juntos",
    "408": "Escritura reflexiva",
    "409": "Uso de servicios digitales",
    "410": "Alimentación saludable (Edad adulta)",
    "411": "Organización y almacenamiento digital de información y datos ",
    "412": "Comunicar y presentar datos",
    "413": "Uso de herramientas colaborativas",
    "415": "Técnico en seguridad - Control de accesos",
    "416": "Técnico en seguridad física y del entorno ",
    "417": "Técnico en radiofrecuencia",
    "418": "Proceso de donación y trasplante de órganos y tejidos",
    "516": "Atrévete a saber",
    "519": "Historia",
    "520": "Centro de Estudios de Historia de México",
    "521": "Museo Soumaya",
    "538": "GIF",
    "539": "Videoblog",
    "540": "Podcast",
    "541": "Digitalízate",
    "542": "Atrévete a crear una app",
    "588": "Donación y trasplante de órganos",
    "590": "ABC sobre vacunación",
    "100001": "Análisis e interpretación de datos",
    "100002": "Gestión del ecosistema digital",
    "100003": "Trámites por internet",
    "100004": "Buenas prácticas para el uso de dispositivos electrónicos",
    "100005": "Seguros cibernéticos",
    "100006": "Compras y pagos seguros por internet",
    "100007": "Introducción a la estadística y probabilidad",
    "100010": "Concentración de agentes contaminantes en el aire ",
    "100058": "Realidad virtual inmersiva",
    "100059": "Responsabilidad social",
    "100060": "Medidas para evitar contagios",
    "100061": "Mérito",
    "100062": "Decisiones complejas",
    "100063": "Solidaridad",
    "100064": "Actitud de servicio",
    "100065": "Uso de asistentes virtuales",
    "100066": "Empatía",
    "100067": "El arte en la vida de los niños",
    "100070": "Juego limpio",
    "100071": "Creación de modelos 3D para entornos virtuales",
    "100072": "Citas y referencias bibliográficas",
    "100074": "Diseño de embalajes sostenibles",
    "100075": "Desarrollador de JavaScript (React)",
    "100084": "Manejo de la voz para medios digitales",
    "100092": "Crea la identidad de tu negocio",
    "100094": "Energía hidroeléctrica para autoconsumo",
    "100095": "Productor de cultivos energéticos",
    "100097": "Constructor de paz digital",
    "100098": "La virtud de servir",
    "100099": "Contaminación acústica",
    "100100": "Identidad digital y firma electrónica",
    "100101": "Retail omnicanal y multicanal",
    "100102": "Autogestión",
    "100103": "Introducción a realidad virtual, aumentada y mixta",
    "100104": "Identificación de información errónea",
    "100105": "Estrategia de precios",
    "100128": "Finanzas para manejar una deuda",
    "100129": "Manejo correcto de las tarjetas de crédito",
    "100135": "Administración del tiempo",
    "100136": "Mente analítica y salud digital",
    "100139": "Autoridad",
    "100140": "Versatilidad",
    "100141": "Planea tu retiro",
    "100142": "La ciencia y los niños",
    "100143": "Finanzas para elegir un seguro",
    "100145": "Comercialización de NFT",
    "100146": "Administrador de bases de datos relacionales",
    "100147": "Finanzas para el hogar ",
    "100148": "Analista de inversiones personales ",
    "100149": "Crea la propuesta de valor para tu negocio ",
    "100150": "Manejo de contingencias",
    "100155": "Manejo de riesgos",
    "100156": "Elige un vehículo con mayor seguridad",
    "100157": "Soldador industrial",
    "100158": "Integridad ",
    "100171": "EI_Embarazo",
    "100172": "EI_Lactancia materna",
    "100173": "EI_Juego",
    "100174": "EI_Derechos",
    "100176": "EI_0 a 3 meses",
    "100177": "EI_3 a 6 meses",
    "100178": "EI_6 a 9 meses",
    "100179": "EI_9 a 12 meses",
    "100180": "EI_12 a 18 meses",
    "100181": "EI_18 a 24 meses",
    "100182": "EI_2 a 3 años",
    "100183": "EI_3 a 4 años",
    "100184": "EI_Todas las edades",
    "100185": "EI_Paternidad activa",
    "100186": "EI_Duelo",
    "100188": "EI_Violencia",
    "100189": "EI_Vínculo y emociones",
    "100190": "EI_Hábitos",
    "100191": "EI_Límites",
    "100192": "EI_Espacios y actividades",
    "100194": "EI_Transición",
    "100195": "EI_Física",
    "100196": "EI_Emocional y mental",
    "100197": "EI_Seguridad y protección",
    "100198": "EI_Tipos",
    "100199": "EI_Inclusión y apoyo",
    "100200": "EI_Accidentes en casa",
    "100202": "EI_COVID-19",
    "100212": "Fundamentos de inteligencia artificial",
    "100213": "Diseñador de peticiones para modelos de IA generativa",
    "100214": "Controlador de plagas en espacios urbanos",
    "100216": "Gestiona tu portafolio como desarrollador",
    "100220": "La música y las emociones",
    "100221": "Creación de físicas e interfaz con C# para RV y RA",
    "100222": "Gánale a la diabetes",
    "100297": "EI_Tecnología",
    "100298": "EI_Buen trato (Campaña)",
    "100310": "Repartidor a domicilio",
    "100311": "Desarrollador PHP (Orientado a objetos)",
    "100312": "La música y el  cerebro  ",
    "100315": "EI_Una alimentación que nutre (Campaña)",
    "100316": "EI_Prevención de la violencia familiar (Campaña)",
    "100317": "Uso de lenguaje corporal ",
    "100320": "Cultura de servicio",
    "100321": "Introducción a la Musicoterapia",
    "100322": "Manejo de dinero",
    "100323": "Manufactura de proximidad (nearshoring)",
    "100324": "Productor de biomasa",
    "100325": "Finanzas para mujeres",
    "100326": "Seguridad vial en motocicletas",
    "100331": "Pensamiento sistémico",
    "100332": "Diseñador de interactivos web",
    "100334": "Introducción a los impuestos",
    "100335": "Diseñador de sitios web dinámicos",
    "100336": "Seguridad en cocinas industriales",
    "100337": "Mente hábil",
    "100343": "Sentido común (Podcast)",
    "100348": "Creando vínculos",
    "100349": "El perdón (Podcast)",
    "100350": "Valentía (Podcast)",
    "100351": "Talento y disciplina (Podcast)",
    "100352": "Libertad (Podcast)",
    "100355": "Culpa (Podcast)",
    "100366": "Hablar para transmitir",
    "100417": "Entorno y desarrollo cerebral del niño",
    "100657": "Introducción a los tipos de interés y tasas",
    "100659": "Diálogo",
    "100676": "Seguridad para trabajos en alturas",
    "100677": "Uso de equipo de protección personal",
    "100678": "Introducción al mantenimiento industrial ",
    "100690": "Introducción a la repostería",
    "100694": "Señalización de tuberías en la industria ",
    "100820": "Desarrollador de aplicaciones móviles.",
    "100827": "IA Generativa",
    "100832": "Pausas activas",
    "100833": "Ejercicios de relajación corporal",
    "100835": "Acondicionamiento físico general",
    "100837": "Calentamiento antes del ejercicio",
    "100839": "Ansiedad: Claves para recuperar la calma"
}